[table]
brightness = 30
ct = 4800
color_mode = false
power_mode = true

  [table.second_light]
  power_mode = false

[desk]
brightness = 100
ct = 4800
color_mode = false
power_mode = true

[couch]
brightness = 100
ct = 4800
color_mode = false
power_mode = true

[bed]
power_mode = false

[desk2]
brightness = 100
ct = 4800
color_mode = false
power_mode = true

[kitchen]
brightness = 100
ct = 5500
color_mode = false
power_mode = true
