[table]
brightness = 1
ct = 2700
color_mode = false
power_mode = true

  [table.second_light]
  red = 255
  green = 0
  blue = 142
  brightness = 100
  color_mode = true
  power_mode = true

[desk]
red = 0
green = 255
blue = 112
brightness = 100
color_mode = true
power_mode = true

[couch]
red = 0
green = 255
blue = 112
brightness = 100
color_mode = true
power_mode = true

[bed]
power_mode = false

[kitchen]
red = 255
green = 0
blue = 165
brightness = 100
color_mode = true
power_mode = true
