[table]
power_mode = false

  [table.second_light]
  red = 255
  green = 0
  blue = 142
  brightness = 100
  color_mode = true
  power_mode = true

[desk]
red = 0
green = 255
blue = 112
brightness = 100
color_mode = true
power_mode = true

[couch]
red = 0
green = 255
blue = 112
brightness = 100
color_mode = true
power_mode = true

[desk2]
red = 0
green = 255
blue = 112
brightness = 100
color_mode = true
power_mode = true

[bed]
red = 255
green = 0
blue = 165
brightness = 100
color_mode = true
power_mode = true

[kitchen]
red = 255
green = 0
blue = 165
brightness = 100
color_mode = true
power_mode = true
