[table]
power_mode = false

  [table.second_light]
  red = 0
  green = 0
  blue = 255
  brightness = 100
  color_mode = true
  power_mode = true

[desk]
red = 255
green = 0
blue = 255
brightness = 100
color_mode = true
power_mode = true

[couch]
red = 255
green = 0
blue = 255
brightness = 100
color_mode = true
power_mode = true

[bed]
red = 255
green = 0
blue = 255
brightness = 100
color_mode = true
power_mode = true

[kitchen]
red = 0
green = 0
blue = 255
brightness = 100
color_mode = true
power_mode = true
