[table]
brightness = 30
ct = 3000
color_mode = false
power_mode = true

  [table.second_light]
  power_mode = false

[desk]
brightness = 100
ct = 3200
color_mode = false
power_mode = true

[couch]
brightness = 100
ct = 3200
color_mode = false
power_mode = true

[desk2]
brightness = 100
ct = 3200
color_mode = false
power_mode = true

[bed]
brightness = 100
ct = 2500
color_mode = false
power_mode = true

[kitchen]
brightness = 100
ct = 2500
color_mode = false
power_mode = true
